
CREATE TABLE AGENCE
(
  IDAGENCE NUMBER   NOT NULL,
  NOM      VARCHAR2 NOT NULL,
  ADRESSE  VARCHAR2 NOT NULL,
  CONTACT  VARCHAR2 NOT NULL,
  CONSTRAINT PK_AGENCE PRIMARY KEY (IDAGENCE)
);

ALTER TABLE AGENCE
  ADD CONSTRAINT UQ_CONTACT UNIQUE (CONTACT);

COMMENT ON COLUMN AGENCE.IDAGENCE IS 'cle primaire';

COMMENT ON COLUMN AGENCE.NOM IS 'nom';

COMMENT ON COLUMN AGENCE.ADRESSE IS 'adresse de l'agence';

COMMENT ON COLUMN AGENCE.CONTACT IS 'contact de l'agence';

CREATE TABLE BIEN
(
  IDBIEN   NUMBER NOT NULL,
  IDPROPRI NUMBER NOT NULL,
  IDAGENCE NUMBER NOT NULL,
  IDSYNDIC NUMBER NOT NULL,
  ADRESSE  NUMBER NOT NULL,
  TYPEBAIL NUMBER NOT NULL,
  SURFACE  NUMBER NOT NULL,
  CONSTRAINT PK_BIEN PRIMARY KEY (IDBIEN)
);

COMMENT ON COLUMN BIEN.IDBIEN IS 'cle primaire';

COMMENT ON COLUMN BIEN.IDPROPRI IS 'proprietaire du bien';

COMMENT ON COLUMN BIEN.IDAGENCE IS 'id de l'agence gerant le bien';

COMMENT ON COLUMN BIEN.IDSYNDIC IS 'syndic concerne par le bien';

COMMENT ON COLUMN BIEN.ADRESSE IS 'adresse du bien';

COMMENT ON COLUMN BIEN.TYPEBAIL IS 'type de bail (1 ou 3 ans)';

COMMENT ON COLUMN BIEN.SURFACE IS 'surface en m2 du bien';

CREATE TABLE DPE
(
  IDBIEN        NUMBER   NOT NULL,
  DATEDEBUT     DATE     NOT NULL,
  DATEFIN       DATE     NOT NULL,
  CLASSEENERGIE CHAR     NOT NULL,
  CLASSECLIMAT  CHAR     NOT NULL,
  CONSO         NUMBER   NOT NULL,
  EMISS         NUMBER   NOT NULL,
  MENTION       VARCHAR2,
  CONSTRAINT PK_DPE PRIMARY KEY (IDBIEN, DATEDEBUT)
);

COMMENT ON COLUMN DPE.IDBIEN IS 'id du bien concerne';

COMMENT ON COLUMN DPE.DATEDEBUT IS 'date de réalisation du DPE';

COMMENT ON COLUMN DPE.DATEFIN IS 'date de fin du DPE';

COMMENT ON COLUMN DPE.CLASSEENERGIE IS 'classe energie du bien';

COMMENT ON COLUMN DPE.CLASSECLIMAT IS 'classe climat du bien';

COMMENT ON COLUMN DPE.CONSO IS 'consomation en kW/h par m2 par an';

COMMENT ON COLUMN DPE.EMISS IS 'emission de CO2 en kg/m2 par an';

COMMENT ON COLUMN DPE.MENTION IS 'mention du bien';

CREATE TABLE LOCATAIRE
(
  IDLOCATAIRE NUM      NOT NULL,
  NOM         VARCHAR2 NOT NULL,
  PRENOM      VARCHAR2 NOT NULL,
  TEL         CHAR(10) NOT NULL,
  MAIL        VARCHAR2,
  IBAN        VARCHAR2 NOT NULL,
  CONSTRAINT PK_LOCATAIRE PRIMARY KEY (IDLOCATAIRE)
);

ALTER TABLE LOCATAIRE
  ADD CONSTRAINT UQ_TEL UNIQUE (TEL);

ALTER TABLE LOCATAIRE
  ADD CONSTRAINT UQ_MAIL UNIQUE (MAIL);

ALTER TABLE LOCATAIRE
  ADD CONSTRAINT UQ_IBAN UNIQUE (IBAN);

COMMENT ON COLUMN LOCATAIRE.IDLOCATAIRE IS 'cle primaire';

COMMENT ON COLUMN LOCATAIRE.NOM IS 'nom du locataire';

COMMENT ON COLUMN LOCATAIRE.PRENOM IS 'prenom du locataire';

COMMENT ON COLUMN LOCATAIRE.TEL IS 'telephone du locataire';

COMMENT ON COLUMN LOCATAIRE.MAIL IS 'adresse email du locataire';

COMMENT ON COLUMN LOCATAIRE.IBAN IS 'coordonees bancaire';

CREATE TABLE LOCATION
(
  IDLOCATION  NUMBER NOT NULL,
  IDBIEN      NUMBER NOT NULL,
  IDLOCATAIRE NUM    NOT NULL,
  DATEDEBUT   DATE   NOT NULL,
  DATEPREVFIN DATE   NOT NULL,
  DATEFIN     DATE  ,
  LOYER       NUMBER NOT NULL,
  CONSTRAINT PK_LOCATION PRIMARY KEY (IDLOCATION)
);

COMMENT ON COLUMN LOCATION.IDLOCATION IS 'cle primaire';

COMMENT ON COLUMN LOCATION.IDBIEN IS 'id du bien concerne';

COMMENT ON COLUMN LOCATION.IDLOCATAIRE IS 'id du loactaire concerne';

COMMENT ON COLUMN LOCATION.DATEDEBUT IS 'date de debut du bail';

COMMENT ON COLUMN LOCATION.DATEPREVFIN IS 'darte de fin prevu du bail';

COMMENT ON COLUMN LOCATION.DATEFIN IS 'date de fin du bail';

COMMENT ON COLUMN LOCATION.LOYER IS 'loyer en euro de la location';

CREATE TABLE PROPRIETAIRE
(
  IDPROPRI NUMBER    NOT NULL,
  NOM      VARCHAR2  NOT NULL,
  PRENOM   VARCHAR2  NOT NULL,
  TEL      CHAR(10). NOT NULL,
  MAIL     VARCHAR2 ,
  IBAN     VARCHAR2  NOT NULL,
  CONSTRAINT PK_PROPRIETAIRE PRIMARY KEY (IDPROPRI)
);

ALTER TABLE PROPRIETAIRE
  ADD CONSTRAINT UQ_TEL UNIQUE (TEL);

ALTER TABLE PROPRIETAIRE
  ADD CONSTRAINT UQ_MAIL UNIQUE (MAIL);

ALTER TABLE PROPRIETAIRE
  ADD CONSTRAINT UQ_IBAN UNIQUE (IBAN);

COMMENT ON COLUMN PROPRIETAIRE.IDPROPRI IS 'cle primaire';

COMMENT ON COLUMN PROPRIETAIRE.NOM IS 'nom';

COMMENT ON COLUMN PROPRIETAIRE.PRENOM IS 'prenom';

COMMENT ON COLUMN PROPRIETAIRE.TEL IS 'numero de telephone';

COMMENT ON COLUMN PROPRIETAIRE.MAIL IS 'adresse email du proprietaire';

COMMENT ON COLUMN PROPRIETAIRE.IBAN IS 'coordonnees bancaire';

CREATE TABLE SYNDIC
(
  IDSYNDIC NUMBER   NOT NULL,
  NOM      VARCHAR2 NOT NULL,
  PRENOM   VARCHAR2 NOT NULL,
  CONTACT  VARCHAR2 NOT NULL,
  CONSTRAINT PK_SYNDIC PRIMARY KEY (IDSYNDIC)
);

ALTER TABLE SYNDIC
  ADD CONSTRAINT UQ_CONTACT UNIQUE (CONTACT);

COMMENT ON COLUMN SYNDIC.IDSYNDIC IS 'cle primaire';

COMMENT ON COLUMN SYNDIC.NOM IS 'nom du syndic';

COMMENT ON COLUMN SYNDIC.PRENOM IS 'prenom du syndic';

COMMENT ON COLUMN SYNDIC.CONTACT IS 'contact du syndic';

CREATE TABLE VISITES
(
  IDBIEN NUMBER   NOT NULL,
  DATE   DATE     NOT NULL,
  HEURE  NUMBER   NOT NULL,
  RETOUR VARCHAR2,
  CONSTRAINT PK_VISITES PRIMARY KEY (IDBIEN, DATE, HEURE)
);

COMMENT ON COLUMN VISITES.IDBIEN IS 'id du bien concerne';

COMMENT ON COLUMN VISITES.DATE IS 'date de la visite';

COMMENT ON COLUMN VISITES.HEURE IS 'heure de la visite';

COMMENT ON COLUMN VISITES.RETOUR IS 'retour du visiteur si existant';

ALTER TABLE LOCATION
  ADD CONSTRAINT FK_BIEN_TO_LOCATION
    FOREIGN KEY (IDBIEN)
    REFERENCES BIEN (IDBIEN);

ALTER TABLE DPE
  ADD CONSTRAINT FK_BIEN_TO_DPE
    FOREIGN KEY (IDBIEN)
    REFERENCES BIEN (IDBIEN);

ALTER TABLE VISITES
  ADD CONSTRAINT FK_BIEN_TO_VISITES
    FOREIGN KEY (IDBIEN)
    REFERENCES BIEN (IDBIEN);

ALTER TABLE LOCATION
  ADD CONSTRAINT FK_LOCATAIRE_TO_LOCATION
    FOREIGN KEY (IDLOCATAIRE)
    REFERENCES LOCATAIRE (IDLOCATAIRE);

ALTER TABLE BIEN
  ADD CONSTRAINT FK_PROPRIETAIRE_TO_BIEN
    FOREIGN KEY (IDPROPRI)
    REFERENCES PROPRIETAIRE (IDPROPRI);

ALTER TABLE BIEN
  ADD CONSTRAINT FK_AGENCE_TO_BIEN
    FOREIGN KEY (IDAGENCE)
    REFERENCES AGENCE (IDAGENCE);

ALTER TABLE BIEN
  ADD CONSTRAINT FK_SYNDIC_TO_BIEN
    FOREIGN KEY (IDSYNDIC)
    REFERENCES SYNDIC (IDSYNDIC);
